apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  labels:
    app: byparr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      dnsConfig: # DNS resolver workaround
        options:
          - name: ndots
            value: "1"
      containers:
      - name: byparr
        image: ghcr.io/thephaseless/byparr:v2.1.0
        ports:
          - containerPort: 8191
        volumeMounts:
          - name: cache-volume
            mountPath: /app/cache

      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: byparr-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
