apiVersion: v1
kind: Service
metadata:
  name: byparr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: byparr
  ports:
  - name: byparr
    protocol: TCP
    port: 8191
    targetPort: 8191
