apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

namePrefix:
  zion-

metadata:
  name: n8n
  namespace: n8n

resources:
  - ../../../base/n8n
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
