apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - open-webui
  # - gitlab
  - immich
  - homeassistant
  - copyparty
  - radarr
  - sonarr
  - flaresolverr
  - prowlarr
  - jellyfin
  - transmission
  - homepage
  # - nextcloud
  - docker-registry
  - docker-registry-ui
  - etl
  - n8n
