apiVersion: v1
kind: Service
metadata:
  name: streamamus
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: streamamus
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9430
