apiVersion: apps/v1
kind: Deployment
metadata:
  name: lili-tarot
  labels:
    app: lili-tarot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lili-tarot
  template:
    metadata:
      labels:
        app: lili-tarot
    spec:
      imagePullSecrets:
      - name: zion-regcred
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: lili-tarot
        image: registry.milanchis.com/lili-tarot:latest
        ports:
          - containerPort: 4321
        env:
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "4321"

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
