apiVersion: v1
kind: Service
metadata:
  name: lili-tarot
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: lili-tarot
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4321
