apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discordamus

namePrefix:
  zion-

metadata:
  name: discordamus
  namespace: discordamus

resources:
  - ../../../base/discordamus
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
