apiVersion: apps/v1
kind: Deployment
metadata:
  name: rawclip
  labels:
    app: rawclip
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rawclip
  template:
    metadata:
      labels:
        app: rawclip
    spec:
      imagePullSecrets:
      - name: zion-regcred
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: rawclip
        image: registry.milanchis.com/rawclip-relay:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 9430
        env:
          - name: RELAY_PORT
            value: "9430"
          - name: BETTER_AUTH_URL
            value: "https://rawclip-relay.milanchis.com"
          - name: BETTER_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: BETTER_AUTH_SECRET
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: TWITCH_CLIENT_ID
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: TWITCH_CLIENT_SECRET
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: GOOGLE_CLIENT_SECRET
          - name: KICK_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: KICK_CLIENT_ID
          - name: KICK_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: KICK_CLIENT_SECRET
          - name: RELAY_OWNER_EMAIL
            valueFrom:
              secretKeyRef:
                name: zion-rawclip-secret
                key: RELAY_OWNER_EMAIL
        volumeMounts:
          - name: data-volume
            mountPath: /app/data

      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: rawclip-pvc

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
