apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rawclip

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - sealedsecret.yaml
  - registry-sealedsecret.yaml
