apiVersion: v1
kind: Service
metadata:
  name: streamsquire-relay
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: streamsquire-relay
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9430
