---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rawclip
  namespace: streamamus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`streamsquire-relay.milanchis.com`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-rawclip
          port: 80
          sticky:
            cookie:
              name: rawclip-stickiness
              secure: true
              httpOnly: true
              sameSite: none
      middlewares:
        - name: zion-rawclip-cors-middleware

  tls:
    secretName: rawclip-certificate-secret
