---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: streamsquire-relay
  namespace: streamamus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`relay.streamsquire.app`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-streamsquire-relay
          port: 80
          sticky:
            cookie:
              name: streamsquire-relay-stickiness
              secure: true
              httpOnly: true
              sameSite: none
      middlewares:
        - name: zion-streamsquire-relay-cors-middleware

  tls:
    secretName: streamsquire-relay-certificate-secret
