apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamamus

namePrefix:
  zion-

metadata:
  name: rawclip
  namespace: streamamus

resources:
  - ../../../base/rawclip
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
