apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: streamamus

namePrefix:
  zion-

metadata:
  name: streamamus
  namespace: streamamus

resources:
  - ../../../base/streamamus
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
