apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamsquire-web
  labels:
    app: streamsquire-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: streamsquire-web
  template:
    metadata:
      labels:
        app: streamsquire-web
    spec:
      imagePullSecrets:
        - name: zion-regcred
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: streamsquire-web
          image: registry.streamsquire.app/streamsquire-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
