apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: streamsquire-web
  namespace: rawclip-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`streamsquire.app`) && PathPrefix(`/`)
      kind: Rule
      priority: 10
      services:
        - name: zion-streamsquire-web
          port: 80
      middlewares:
        - name: zion-streamsquire-web-cors-middleware
  tls:
    secretName: streamsquire-web-certificate-secret
