apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rawclip-web

namePrefix: zion-

resources:
  - ../../../base/rawclip-web
  - certificate.yaml
  - ingress.yaml
  - middleware.yaml
